name: Build Flask & Spring Boot

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push Flask image
        uses: docker/build-push-action@v4
        with:
          context: ./flask
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/flask-app:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/flask-app:${{ github.run_number }}
          file: ./flask/Dockerfile

      - name: Build and push Spring Boot image
        uses: docker/build-push-action@v4
        with:
          context: ./springboot
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/springboot-app:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/springboot-app:${{ github.run_number }}
          file: ./springboot/Dockerfile


