name: Build Flask

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v2
        with:
            buildkitd-flags: --allow-insecure-entitlement security.insecure --allow-insecure-entitlement network.host

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
            context: ./flask
            push: true
            tags: |
              ${{ vars.DOCKER_HUB_USERNAME }}/flask-app:latest
              ${{ vars.DOCKER_HUB_USERNAME }}/flask-app:${{ github.run_number }}
            file: ./flask/Dockerfile